services:
  nginx:
    image: nginx:stable-alpine
    ports:
    - 8080:80
    volumes:
    - .:/var/www/html:ro
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
    - php
    restart: unless-stopped

  php:
    build: ./php
    volumes:
    - .:/var/www/html:ro
    - ./php/general.inc.php:/var/www/html/cfg/general.inc.php:ro
    - ./partials_c:/var/www/html/partials_c
    - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    depends_on:
    - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.4
    ports:
    - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: test
    volumes:
    - ./test.sql.xz:/docker-entrypoint-initdb.d/test.sql.xz:ro
    - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: